@CleanTeeth.API_HostAddress = http://localhost:5073/api


GET {{CleanTeeth.API_HostAddress}}/dentists
Content-Type: application/json

###
GET {{CleanTeeth.API_HostAddress}}/dentists/01a11246-02c2-7ed3-9d43-e42e38f69a32
Content-Type: application/json

###

POST {{CleanTeeth.API_HostAddress}}/dentists
Content-Type: application/json

{
  "name": "Dentist Lantern",
  "email": "DentistLantern@example.com"
}

###
PUT {{CleanTeeth.API_HostAddress}}/dentists/01a11247-0c11-7969-ae1c-95ae86c9c4c3
Content-Type: application/json

{
  "name": "Green Dentist Lantern",
  "email": "GreenDentistLantern@example.com"
}

###

