@CleanTeeth.API_HostAddress = http://localhost:5073/api


GET {{CleanTeeth.API_HostAddress}}/dentists
Content-Type: application/json


###

POST {{CleanTeeth.API_HostAddress}}/dentists
Content-Type: application/json

{
  "name": "Dentist Lantern",
  "email": "DentistLantern@example.com"
}
