@CleanTeeth.API_HostAddress = http://localhost:5073/api


GET {{CleanTeeth.API_HostAddress}}/patients
Content-Type: application/json

###
GET {{CleanTeeth.API_HostAddress}}/patients/01a0fd63-22b3-7717-8873-13fa56527a65
Content-Type: application/json

###

POST {{CleanTeeth.API_HostAddress}}/patients
Content-Type: application/json

{
  "name": "Lupis Cuevas",
  "email": "Lupis@example.com"
}

###
