@CleanTeeth.API_HostAddress = http://localhost:5073/api

POST {{CleanTeeth.API_HostAddress}}/patients
Content-Type: application/json

{
  "name": "Ernesto Cardenas",
  "email": "ernesto.cardenas@example.com"
}

###
